spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    database: mysql
    generate-ddl: true
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/copykiller?useUnicode=true&characterEncoding=utf8
    username: copykiller
    password: ehdir2.0
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/template/
    suffix: .html
logging:
  level:
    orgspringframework.transaction.interceptor: TRACE
server:
  port: 8080
